import { createContext, useState } from "react";

export const BollywoodContext = createContext()

const BollywoodContextProvider = (props) => {
    const [bollywood] = useState([{
        id: "51",
        tittle: "Flashback | With the demise of Amrish Puri, entire era of screen villainy came to an end",
        image: "/images/bollywood/Amrish.webp",
        date: "January 12, 2022",
        author: "By Subhash K Jha",
        category: "Bollywood",
        description: "Amrish Puri was a one-man army, ploughing easily from Shyam Benegal’s classy and raw Nishant to the out-and-out potboilers that he did through the 1980s and '90s.",
        article: `“Mogambo khush hua,” the booming menacing baritone in Shekhar Kapur’s Mr. India defines the career of the  sinfully talented Amrish Puri. He was a one-man army, ploughing easily from Shyam Benegal’s classy and raw  Nishant to the out-and-out potboilers that he did through the 1980s and '90s. “I just kept working and working. I had seen hard times. I didn’t want to lose the opportunity to make a living. Luckily, for me, there was no dearth of work. I could do offbeat films for free, and compensate by doing the  commercial films. It was, according to me, a fair deal,” Puri told me. In his 30-year career as an actor, Puri did over 200 films. In his early years, most of the work he did was either quality-oriented work  for the avant garde directors Shyam Benegal and Govind Nihalani or outright kitsch, where he used his powerful voice and screen presence to accentuate the cinematic  definitions of evil. Puri’s truly fecund phase as Bollywood’s most dependable character-actor, or actor of character, began in 1992. In Benegal’s Nishant (1975), Puri played the eldest brother in a family of zaalim (cruel) zamindars who abduct and rape a schoolteacher’s wife. Puri struck a note of immediate and everlasting terror in viewers’ hearts. Though the film had other terrific actors, it was Puri who dominated the show in every way possible. The role had apparently been written for the Bengali actor Utpal Dutt, who excelled at playing obdurate disciplinarians. Puri too went on to make a great impression on mainstream Hindi cinema as the unrelenting patriarch. In 1992, Puri  chanced on  huge commercial success with Phool Aur Kaante. Though this was the launchpad for Ajay Devgn, it was Puri who stole much of the dubutant’s thunder as the good-natured don who wants to win his  estranged son’s respect back. Puri admitted this film was a turning point in his career. During the same year that Phool Aur Kante brought grey glory into Puri’s black persona, he went out-and-out benign in Priyadarshan’s Muskurahat, a wonderfully heartwarming story of a sullen old man, and a young woman who brings a smile to his frowning face. In the two pivotal roles, Puri amd Revathi were outstandingly synchronised. Priyadarshan went on to cast Puri in most of Hindi films, including Hulchul (2004), where the actor played an obdurate village leader who goes to any lengths to settle scores with his enemies.`
    },
    {
        id: "52",
        tittle: "Dhanush, Aishwaryaa announce separation, Bachchan Pandey to release in March, and more such news",
        image: "/images/bollywood/Dhanush.jpg",
        date: "January 18, 2022",
        author: "By FP Staff",
        category: "Bollywood",
        description: "Dhanush, Aishwaryaa announce separation after '18 years of togetherness': 'We stand at a place where our paths separate'",
        article: `South star Dhanush on Monday announced separation from his filmmaker wife Aishwaryaa Rajinikanth after 18 years of marriage. Dhanush and Aishwarya, daughter of megastar Rajinikanth, tied the knot in 2004 and are parents to two sons, Yatra and Linga, who were born in 2006 and 2010, respectively. Dhanush, 38, and Aishwaryaa, 40, shared a note announcing their separation on their respective social media accounts. "Eighteen years of togetherness as friends, couple, as parents and well wishers to each other. The journey has been of growth, understanding, adjusting and adapting. Today we stand at a place where our paths separate. Aishwaryaa and I have decided to part ways as a couple and take time to understand us as individuals for the better. "Please do Respect our decision and give us the needed privacy to deal with this. Om Namashivaaya! Spread love, D," Dhanush shared in a note on Twitter. Aishwaryaa shared the same note on Instagram and captioned it: "No caption needed…only your understanding n your love necessary!" Dhanush and Aishwarya, daughter of actor Rajinikanth, tied the knot in 2004. They are parents to two sons, Yatra and Linga, who were born in 2006 and 2010, respectively. Aishwaryaa has directed films like the Tamil romantic thriller "3" and black comedy "Vai Raja Vai". Dhanush, also a producer, was recently seen in the Aanand L Rai directed Hindi romantic drama Atrangi Re and has a long career in the Tamil film industry. `
    },
    {
        id: "53",
        tittle: "As Ranveer Singh's 83 crosses Rs 100 cr at box office, Dulquer Salmaan's Salute gets postponed",
        image: "/images/bollywood/kapildev.jpg",
        date: "January 11, 2022",
        author: "By FP Staff",
        category: "Bollywood",
        description: "Ranveer Singh-starrer 83 slowly but surely crossed Rs 100 crore in 17 days. Meanwhile, owing to theatre shutdowns in my states, Dulquer Salmaan chose to postpone his Malayalam film Salute.",
        article: `Filmmaker Kabir Khan’s cricket drama 8324 has touched the Rs 100 cr mark at the domestic box office, the makers said on Monday. Seventeen days since its release, the all-India collections of the Ranveer Singh-headlined film now stands at Rs 100.56 cr. The movie was released in Hindi, Tamil, Telugu, Kannada and Malayalam on 24 December. 83 was dubbed as an underperformer by trade analysts as the multistarrer failed to maintain the momentum of the Hindi film box office following the mammoth success of Akshay Kumar’s 2021 Diwali release Sooryavanshi – the only Bollywood blockbuster of last year. In an earlier interview with PTI, Khan had defended the film’s collection by calling 83 a “victim of the pandemic” and said the movie put up a show despite battling COVID-19 restrictions like closure of cinema halls in certain states and theatrical occupancy cap in key territories. The film chronicled India’s win under Kapil Dev’s captainship, when the team defeated the mighty West Indies in the final to clinch their first-ever World Cup trophy in 1983. Meanwhile, actor Dulquer Salmaan on Monday said his upcoming Malayalam crime thriller Salute has been pushed from its scheduled release of 14 January due to the rising coronavirus cases in the country.“We at Wayfarer films are bound to show social responsibility ahead of our personal interests. Just like all of you, we were most excited and eagerly awaiting our next release. “Owing to recent developments and the spike in Covid-19 and Omicron cases, we have taken the difficult decision to postpone the release of ‘Salute’. We apologise if we’ve disappointed you. But in times like this we must prioritise health and safety,” the note read. The Kurup star assured his fans that the film will be released “at the earliest”. Directed by Rosshan Andrrews, the film features Salmaan as a cop and also stars Diana Penty. Salute is the latest project to have deferred its release after films like Shahid Kapoor’s Jersey, filmmaker SS Rajamouli’s RRR, Prabhas starrer Radhe Shyam and Valimai, featuring Ajith Kumar had to push their releases due to the pandemic.`
    },
    {
        id: "54",
        tittle: "Watch: Shireen Mirza drops throwback video of ‘acting school days’ with Vicky Kaushal",
        image: "/images/bollywood/vicky.webp",
        date: "January 18, 2022",
        author: "By FP Trending",
        category: "Bollywood",
        description: "Shireen Mirza, who went to acting school along with Vicky Kaushal has shared a throwback video on social media which has now gone viral ",
        article: `Yeh Hai Mohabbatein actress Shireen Mirza recently conducted an 'Ask Me Anything' session on her Instagram handle. While interacting with her fans, one ardent follower requested her to share an image or video with National Award-winning actor Vicky Kaushal as they both have been to acting school together. Without wasting much time, Mirza took her fans down memory lane with an epic throwback video with the Uri actor. She shared a video of their skit on Instagram stories and captioned it saying, “Jab hum chote bachhe the (when we used to be kids).” She also added laughing emojis to her post. In another slide of her stories, Mirza apologised to Kaushal for posting the video. She shared an emoji with folded hands for posting the clip. Reacting to the same, the Raazi actor reposted it and said ‘Good old acting school days (2009)’ and added a few laughing emojis too. For the unversed, Vicky Kaushal started his Bollywood career as an assistant director to filmmaker Anurag Kashyap. The Sunju actor worked with the renowned filmmaker in Gangs Of Wasseypur (2012). During the same time, Kaushal made his debut in Luv Shuv Tey Chicken Khurana with a small role. After a long wait, Vicky Kaushal got his first break as a lead actor in Masaan that released in 2015. From then onwards, it was no turning back for him. The actor was last seen in Sardar Udham that released in 2021. It also opened to stellar reviews and Vicky’s acting was much appreciated across the country. On the work front, Vicky Kaushal is currently shooting for his upcoming project alongside actor Sara Ali Khan in Indore. Reports suggest that he has been offered a role in Farhan Akhtar's Jee Le Zaraa, which stars Priyanka Chopra, Alia Bhatt and Katrina Kaif in the lead.`
    },
    {
        id: "55",
        tittle: "Will Aryan Khan's controversy lead to more stars sending their kids to study abroad?",
        image: "/images/bollywood/aryan.webp",
        date: "January 12, 2022",
        author: "By Subhash K Jha",
        category: "Bollywood",
        description: "Aamir Khan’s words in 2015 about the safety of his children now reverberate across the entertainment industry, thanks to the Aryan Khan case.",
        article: `Star kids are a breed under attack. Or so Bollywood’s parents seem to believe. After Shah Rukh Khan’s son Aryan  was arrested on charges of narcotics consumption on Gandhi Jayanti last year, parents of star children have begun to do an auto-rethink on their wards’ future. Is it safe for star kids to stay in India? No seems to be the current answer. A star-parent, whose son was launched with much fanfare last year (and who is not a Muslim), admitted  things do not look good for star children in this country. “And I mean privileged children from any walk of life, why just the  entertainment industry? But yes, more eyes are focused on celebrities from the glamour industry. Our children are more vulnerable than children of entrepreneurs and politicians because we are more loved by people.” This star-father admitted he would have had second thoughts about a career for his son in Bollywood if the Aryan episode had happened earlier. Parents in Bollywood are seriously thinking of packing off their children to ‘safer’ places. Nawazuddin Siddiqui’s two children are now being schooled in Dubai. Saif Ali Khan and Kareena Kapoor Khan’s two children, Taimur and Jehangir, will attend boarding school in England just like their father and two aunts (Saba and Soha Ali Khan). Aamir Khan’s words in 2015 about the safety of his children now reverberate across the entertainment industry. At a summit, Aamir had said, "When I chat with Kiran (Rao, then-wife) at home, she says ‘Should we move out of India?’ That’s a disastrous and big statement for Kiran to make. She fears for her child. She fears about what the atmosphere around us will be. She feels scared to open the newspapers every day. People who are our elected representatives, people who we select to look after us for five years, state or centre, when people take law into their hands, we look upon these people to take a strong stance, to make a strong statement, speed up the legal process, when we see that happening, there is a sense of security but when we don’t see that happening, there is a sense of insecurity.”`
    },
    {
        id: "56",
        tittle: "I’ve been leading a selfish life: Pratik Gandhi talks about stealing moments with wife for marital happiness",
        image: "/images/bollywood/pratik.webp",
        date: "January 18, 2022",
        author: "By Titas Chowdhury",
        category: "Bollywood",
        description: "Even before he became an overnight sensation, post the success of his web show, Scam 1992: The Harshad Mehta Story, actor Pratik Gandhi had a chock-o-block schedule.",
        article: `Recalling those days, he shares, “I done been multiple things simultaneously over the years including a full-time job, doing theatre, going for rehearsals, travelling for shows and attending to medical emergencies at home. I never had any leisure time for myself. I don’t remember taking vacations, trips or even weekend getaways in all those years.” And being constantly busy did affect his relationship with wife, actor Bhamini Oza Gandhi, who he married in 2009. Talking about how his wife felt, Gandhi says, “My wife and I have had multiple discussions and fights all these years about how busy I am. She kept asking me, ‘What are you running for? When will it end? When will we get time for ourselves?’ I agree that I have been leading a very selfish life.” Today, his wife is happy with the way Gandhi’s career has shaped up and the way they are living “a joint dream”. However, the couple still struggles with taking out time and spending moments together. “We often slip away for stolen moments, steal them. We try travelling together. There was this episode when I was in the middle of changing flights. I landed at the airport after shooting somewhere for about a month and was going somewhere else for ten more days. I called her to the airport and we met there,” the 41-year-old shares. This year will see the Bhavai (2021) actor in five projects where he will be sharing screen space with actors Vidya Balan, Taapsee Pannu and Richa Chadha, among others. Quiz him if he fears being overpowered by them and he candidly says, “Not at all! When we had reading sessions, I realised the journeys of my characters in these projects were such that there was a lot of scope and room to overpower each other. Having said that, these actors are so secured in their own space and they’re extremely professional.”`
    },
    {
        id: "57",
        tittle: "Rajkummar Rao to play visually impaired industrialist Srikanth Bolla in upcoming biopic",
        image: "/images/bollywood/Rajkummar.webp",
        date: "January 06, 2022",
        author: "By FP Trending",
        category: "Bollywood",
        description: "Directed by Tushar Hiranandani, the shooting of the biopic will start in July this year, according to trade analyst Taran Adarsh. The film will be produced by Nidhi Parmar Hiranandani, Bhusan Kumar and Krishna Kumar.",
        article: `Tushar Hiranandani, who is known for his film Saand Ki Aankh starring Taapsee Pannu and Bhumi Pednekar, will helm the biopic on the life Bollant industries founder Srikanth Bolla. Bolla was born visually impaired in Seetharamapuram in Andhra Pradesh’s Machilipatnam. The youngster who wanted to pursue Science for his secondary education, was refused permission by his school, according to a Deccan Chronicle report. After taking the matter to court, Bolla was finally allowed to pursue Science, but “at his own risk”. Bolla cleared his 12th Boards with 98 percent marks and went on to become the first international visually-impaired student to attend the Massachusetts Institute of Technology (MIT). After graduating, the young entrepreneur chose to come back to India and start Bollant Industries, which manufactures Areca-based products. According to Tushar Hiranandani, he wanted to make a film on Bolla even before Saand Ki Aankh, but could not do so due to a variety of reasons. The biopic will trace Bolla’s journey from his birth and continue to time at MIT and how he came back to the country, despite many opportunities being offered to him in the US. As for Rao, apart from biopic, the actor is set to star opposite Bhumi Pednekar in the film Badhaai Do. The movie is a sequel to the 2018 hit Badhaai Ho. He will also feature in HIT - The First Case opposite Sanya Malhotra, Anubhav Sinha's Bheed and Netflix’s Monica, O My Darling.`
    },
    {
        id: "58",
        tittle: "Sara Ali Khan deconstructs her character Rinku from Atrangi Re: 'I could relate to her idealised version of love'",
        image: "/images/bollywood/Sara.webp",
        date: "January 07, 2022",
        author: "By Subhash K Jha ",
        category: "Bollywood",
        description: "'Whether it’s our personal life or professional life, somewhere we all have an idealised version of what we would want or desire in life. Rinku is the same, so am I.",
        article: `I’m overwhelmed, to say the least. My character Rinku and the film Atrangi Re will forever be a part of me. The film has given me a lifetime of memories. The feedback I’ve been receiving is humbling and very motivating, especially at this early phase of my career. My friends, family, fans, the industry have had some very nice things to say and I’m truly thankful for that. But the fact that I’ve been able to make my parents cry, and make my brother proud, and even my grandmother… that for me is a huge achievement. As a girl who’s a diehard romantic at heart, and an idealistic person by nature I have definitely grown up imagining a ‘perfect’ or ‘ideal’ love. In fact in Atrangi Re, the fact that Rinku has a perfect idealised version of her love is so relatable to me. 2021 has been quite a bittersweet year. We are in the midst of a pandemic, but Atrangi Re was the small bubble I escaped into that gave me solace and motivation. It gave me great memories to replace the bad ones. It was also a wonderful moment for the family when Jehangir was born and I do try to spend time with him and Taimur whenever I get the chance. I’ve seen a lot of my grandmother’s work and not just because she happens to be my grandmother but also because she is an icon of Indian cinema. In fact one of the biggest compliments I’ve received was her appreciating my performance in Atrangi Re. She even got messages from her friends and family members appreciating my performance in Atrangi, which was very encouraging. The fact that I have been able to make her proud is a huge achievement for me. She will always be the epitome of grace and beauty for me. I think no one has escaped from the Covid aftermath and it’s been tough on everyone. I choose to stay positive and that’s the way I dealt with the ‘new normal’. Of course spending that extra time with my family, catching up on some books and staying disciplined with my workout regime was an added bonus.`
    }
    ])
    return (
        <BollywoodContext.Provider value={{ bollywood }} >
            {props.children}
        </BollywoodContext.Provider>
    )
}
export default BollywoodContextProvider;