import { createContext,useState } from "react";

export const BusinessContext = createContext()

const BusinessContextProvider =(props)=>{
        const [business] =useState([{
            id:"21",
            tittle:"Synchronised global regulation of crypto needed: PM Modi at WEF",
            image:"/images/business/pmmodi.webp",
            date:"January 17, 2022",
            author:"By: Asit Ranjan Mishra ",
            category:"Business",
            description:"Prime Minister Narendra Modi on Monday called for synchronised global action to regulate cryptocurrencies, at a time when India is contemplating bringing a legislation to regulate such virtual currencies.",
            article:"Speaking at the virtual summit of the World Economic Forum, Modi said that steps taken by one country to regulate cryptocurrencies may not be sufficient, given the kind of technology involved. “Today with change in global order, the challenges we face are also increasing. To fight these challenges, every country and every international organisation needs to take collective and synchronised action. Supply chain disruption, inflation and climate change are such examples,” Modi said. “Another example is cryptocurrency. The kind of technology that is linked to it, steps taken by one country will be insufficient to face such challenges. We have to take one view on it.” Modi also called for the reform of multilateral organisations, such as the International Monetary Fund, as he expressed doubt on whether they are capable of tackling such new challenges. “Looking at the global scenario, the question is whether multilateral organisations in the new world order are ready and capable to tackle such challenges. When these organisations were established, the circumstances were different. Today, the situation is different. That’s why it is the responsibility of all democratic countries to emphasise reform of such institutions so that they can be readied to face today’s and tomorrow’s challenges,” he said. Last month, Finance Minister Nirmala Sitharaman had said that global action can manage borderless technology and no country has a one-point formula. 'Even as we are thinking at a national level', 'there should simultaneously be a global mechanism through which we are constantly monitoring the movement of technology,' she had said at an event."
        },
        {
            id:"26",
            tittle:"India's richest doubled their wealth to $720 bn during Covid crisis: Oxfam",
            image:"/images/business/richest.webp",
            date:"January 17, 2022",
            author:"By Archana Chaudhary ",
            category:"Business",
            description:"India added 40 billionaires to 142 last year, when a second wave of Covid overwhelmed its health infrastructure and pushed crematoriums and burial grounds to breaking point, says the report",
            article:"India’s richest have more than doubled their fortunes during the Covid-19 crisis that’s ravaged the country and worsened poverty, and the government should revisit its policies to redistribute wealth, according to the global Oxfam Davos report of 2022. The nation added 40 billionaires to 142 last year, when a second wave of infections overwhelmed its health infrastructure and pushed crematoriums and burial grounds to breaking point. They have almost $720 billion in combined fortune, more than the poorest 40% of the population, the group said in a report on rising inequality published Monday. Wealth has surged globally during the pandemic as the value of everything from stock prices to crypto and commodities has jumped. The world’s 500 richest people added more than $1 trillion to their net worths last year, according to the Bloomberg Billionaires Index. India, where urban unemployment climbed as high as 15% last May and food insecurity worsened, now counts more billionaires than France, Sweden and Switzerland combined, Oxfam said. State policies including the abolition of a wealth tax in 2016, steep cuts in corporate levies and an increase in indirect taxation are among the factors that helped make the rich richer, while the national minimum wage has remained at Rs 178 ($2.4) a day since 2020, the India supplement of the global report said. Reduced federal funding to local administrations amid growing privatisations in the health and education sectors have further boosted inequalities. The nation is home to a quarter of the world’s undernourished people, Oxfam said, citing the World Food Programme."
        },
        {   
            id:"22",
            tittle:"Walmart is quietly preparing to enter the metaverse",
            image:"/images/business/walmart.jpg",
            date:"January 16, 2022",
            author:"By Lauren Thomas",
            category:"Business",
            description:"Walmart appears to be venturing into the metaverse with plans to create its own cryptocurrency and collection of NFTs. The big-box retailer filed several new trademarks late last month that indicate its intent to make and sell virtual goods.",
            article:"Walmart appears to be venturing into the metaverse with plans to create its own cryptocurrency and collection of nonfungible tokens, or NFTs. The big-box retailer filed several new trademarks late last month that indicate its intent to make and sell virtual goods, including electronics, home decorations, toys, sporting goods and personal care products. In a separate filing, the company said it would offer users a virtual currency, as well as NFTs. According to the U.S. Patent and Trademark Office, Walmart filed the applications on Dec. 30. In total, seven separate applications have been submitted. In a statement, Walmart said it is 'continuously exploring how emerging technologies may shape future shopping experiences.' It declined to comment on the specific trademark filings. 'We are testing new ideas all the time,' the company said. 'Some ideas become products or services that make it to customers. And some we test, iterate, and learn from.' 'They’re super intense,' said Josh Gerben, a trademark attorney. 'There’s a lot of language in these, which shows that there’s a lot of planning going on behind the scenes about how they’re going to address cryptocurrency, how they’re going to address the metaverse and the virtual world that appears to be coming or that’s already here.' Gerben said that ever since Facebook announced it was changing its company name to Meta, signaling its ambitions beyond social media, businesses have been rushing to figure out how they will fit into a virtual world. Launching NFTs allows for businesses to tokenize physical products and services to help reduce online transaction costs, it said. And for luxury brands like Gucci and Louis Vuitton, NFTs can serve as a form of authentication for tangible and more expensive goods, CB Insights noted. Gerben said that as more consumers familiarize themselves with the metaverse and items stored on the blockchain, more retailers will want to create their own ecosystem around it. According to Frank Chaparro, director at crypto information services firm The Block, many retailers are still reeling from being late to e-commerce, so they don’t want to miss out on any opportunities in the metaverse."
        },
        {
            id:"23",
            tittle:"Indian CEOs worry more now about health risks impacting top line: PwC study",
            image:"/images/business/indianceo.jpg",
            date:"January 17, 2022",
            author:"By Asit Ranjan Mishra",
            category:"Business",
            description:"While 99% Indian CEOs polled this year believed India's economic growth will improve in next 12 months, the survey conducted before third wave outbreak raises fresh questions about the outlook",
            article:"About 89 per cent of India’s chief executive officers (CEOs) are concerned about health risks adversely impacting their top line in the next 12 months. This is 9 percentage points higher than what their global counterparts think, according to a CEO survey conducted by audit firm PwC before the onset of the third wave. “This is perhaps an indication that business leaders would like to exercise caution when it comes to making early investment and business decisions, despite vaccination drives worldwide. Concern over the ability to attract and retain talent is also strongly ...   As we near the two-year mark of the pandemic, the global economy has rebounded from the depths of mid-2020. The IMF projects global GDP to grow 4.9% in 2022, a downtick from the 5.9% growth expected in 2021, but still formidable. The 4,446 CEOs from 89 countries and territories who responded to our 25th Annual Global CEO Survey display optimism about continued economic resilience. Yet threats, uncertainties and tensions abound. The survey was in the field during the COP26 conference in Scotland, which convened world leaders to try to prevent the worst effects of climate change. PwC experts who attended were both impressed by executives’ commitment to rapid progress and aware that the captains of industry in Glasgow were a self-selected group that came prepared to take action. The question of how to bring others along looms large. Then, just two weeks after our survey closed, news of the Omicron variant reverberated around the world, raising fresh questions about the course of the pandemic and about society’s ability to continue the slow climb to normalcy. Our survey findings reflect these and other tensions. For example, just 22% of survey respondents have made net-zero commitments (though the largest companies in our sample are further along). CEOs are most worried about the potential for a cyberattack or macroeconomic shock to undermine the achievement of their company’s financial goals—the same goals that most executive compensation packages are still tied to. And they are less concerned about challenges, like climate change and social inequality, that appear to pose smaller immediate threats to revenue."
        },
        {
            id:"27",
            tittle:"Why retail investing has taken off in the U.S. — but not Europe",
            image:"/images/business/retail.jpg",
            date:"January 14, 2022",
            author:"By Julianna Tatelbaum",
            category:"Business",
            description:"European retail investor participation has always been low relative to other advanced economies. Could that change?",
            article:"European retail investing has always been tepid relative to other advanced economies. The recent boom in American trading activity on platforms such as Robinhood has made that discrepancy even more visible. While Europe has seen retail investor participation double since 2020, Vanda Research found retail activity still makes up only 5-7 percent of total trading volume in Europe, compared to more than 25 percent in the U.S. and more than 60 percent in China. Despite that, there is a slew of start-ups in Europe trying to take advantage of growing interest, including Revolut, Trading 212, Freetrade and Trade Republic. Watch the video above to learn why retail investing has lagged in Europe, and whether a large pension gap, low interest rates and a raft of new online brokerages hitting the market could build enough momentum to change that. "
        },
        {
            id:"24",
            tittle:"Spends on tech are only going to increase: HCL Tech chief C Vijayakumar",
            image:"/images/business/hcl.webp",
            date:"January 17, 2022",
            author:"By Shivani Shinde",
            category:"Business",
            description:"In a Q&A, the company's CEO & MD dwells on the firm's growth momentum, supply challenges and demand. HCL Technologies revenue growth numbers for the third quarter of FY22 came in at the highest at 7.6 per cent on constant currency basis sequentially.",
            article:"HCL Technologies revenue growth numbers for the third quarter of FY22 came in at the highest at 7.6 per cent on constant currency basis sequentially. However, supply side constraints and higher retention cost impacted the firm's margin performance as well as profits, which was one of the reasons for the firm's stock price to fall by almost 5 per cent in early trade. In an interview C Vijayakumar, CEO and MD, HCL Technologies talks with Shivani Shinde about growth momentum, supply challenges and demand. Edited excerpts You said Q3 was one of the best quarters in 12 years. CEO C Vijayakumar has taken over as the managing director of HCL Technologies after co-founder Shiv Nadar stepped down as MD on July 19 after 45 years with the firm during which the company reached the milestone of $10 billion in revenues. While the 76-year-old Nadar, who will continue as the strategic adviser to the board, has been named the Chairman Emeritus, it will be Vijayakumar, 53, who will be in the hot seat. In an interview to Moneycontrol, Vijayakumar talks about his new role, the demand environment, the hiring boom and investments. Edited excerpts:I think the day-to-day business operations, I was already fully learning it. But definitely certain very long-term strategic initiatives he was very focused on, ideally looking at what would the next 10 years or 15 years look like, and what kind of initiatives that we lay the foundation on. Our investment had multiple things. One is new geographies and also strengthening the sales teams in our products and platform business, and also building a little more digital engineering capabilities on the engineering and R&D side. So these three together were 1 percent incremental investments that we were making. So if you take it to over two years, then it is $200 million."
        },
        {
            id:"25",
            tittle:"China’s economy grew 8.1% in 2021 compared to a year ago",
            image:"/images/business/chinagdp.jpeg",
            date:"January 15, 2022",
            author:"By Evelyn Cheng",
            category:"Business",
            description:"Fourth-quarter GDP rose by 4% from a year earlier, according to China’s National Bureau of Statistics. Analysts polled by Reuters had expected China to report fourth-quarter GDP growth of 3.6%.",
            article:"BEIJING — China’s economy grew by 8.1% in 2021 as industrial production rose steadily through the end of the year and offset a drop off in retail sales, according to official data from China’s National Bureau of Statistics released Monday. Fourth-quarter GDP rose by 4% from a year ago, according to the statistics bureau. That’s faster than the 3.6% increase forecast by a Reuters poll. For the full year, China economists expected an average of 8.4% growth in 2021, according to financial data provider Wind Information. Industrial production rose by 4.3% in December from a year ago, the bureau said, also beating Reuters’ forecast of 3.6% growth. Notably, auto production grew for the first time since April, up by 3.4% year-on-year in December. Fixed asset investment for 2021 grew by 4.9%, topping expectations for 4.8% growth. Investment in real estate rose by 4.4%, while that in infrastructure rose by 0.4%. Investment in manufacturing grew by 13.5% in 2021 from a year ago, with that in special purpose machinery rising the most, up by 24.3% year-on-year, according to data accessed through Wind. However, retail sales missed expectations and grew by 1.7% in December from a year ago. Analysts polled by Reuters had predicted a 3.7% increase. 'We must be aware that the external environment is more complicated and uncertain, and the domestic economy is under the triple pressure of demand contraction, supply shock and weakening expectations,' the bureau said in a statement."
        },
        {
            id:"28",
            tittle:"Budget 2022-23: Govt likely to target 13-14% nominal growth in FY23",
            image:"/images/business/budget.jpg",
            date:"January 17, 2022",
            author:"By Asit Ranjan Mishra ",
            category:"Business",
            description:"The Union Budget for FY23 is likely to assume 13-14 per cent nominal GDP growth despite the growing inflationary concerns. According to finance ministry officials, the assumption of even faster nominal GDP growth may raise inflationary expectations, giving wrong signals to the market.",
            article:"For FY22, the Budget assumed 14.4 per cent gro­wth in nominal GDP. But the latest first Advance Esti­m­ates of GDP for the year released by the National Stati­stical Office put nominal GDP at 17.6 per cent, with an implicit GDP defl­ator of 8.4 per cent, signalling that the finance. Budget FY23 is likely to have two focal points: (1) striking a balance between fiscal consolidation and supporting economic activity, especially amid the uncertainty surrounding a new COVID-19 wave in FY23, and (2) any tax change announcements, which could pave the way for Euroclear eligibility for Indian government bonds (IGBs), and eventually, their inclusion in one of the major global bond indices. We believe the Centre is likely to announce a fiscal deficit target of 6% of GDP for FY23, assuming that the FY22 fiscal deficit target is in the range of 6.5-6.8% of GDP; we think the FY22 fiscal deficit is likely to be towards the lower end rather than the upper end of the band, as nominal GDP growth of 17.6% and tax collections have been much better than budgeted. The key question is whether such fiscal deficit consolidation will allow space for nurturing growth. We think so, for a host of reasons. Relative to the pre-pandemic phase, when the fiscal deficit ranged from 3.5-4% of GDP, a 6% fiscal deficit provides enough room to the government to support growth. However, one could argue that a 6% FY23 fiscal deficit target is probably only‘optically wider’, as GDP contracted in FY21. However, based on our estimate, even if we assume that GDP in FY20-FY23 grows in line with trend (five-year average GDP growth of FY15-19), expenditure as a percentage of GDP in FY23 would still be close to 13.5% of GDP versus the pre-pandemic average of 12.8% of GDP. It is equally interesting to note that while most of this increase in expenditure since the Covid outbreak has been driven by subsidies, interest payments, etc,capital expenditure has risen too. For instance, capital expenditure is hovering at around 2.1-2.2% of GDP since FY21 (we expect a similar trend in FY23) versus the pre-pandemic average of 1.7% of GDP."
        }
    ])

    const [top] = useState([
        {   
            id:"22",
            tittle:"Walmart is quietly preparing to enter the metaverse",
            image:"/images/business/walmart.jpg",
            date:"January 16, 2022",
            author:"By Lauren Thomas",
            category:"Business",
            description:"Walmart appears to be venturing into the metaverse with plans to create its own cryptocurrency and collection of NFTs. The big-box retailer filed several new trademarks late last month that indicate its intent to make and sell virtual goods.",
            article:"Walmart appears to be venturing into the metaverse with plans to create its own cryptocurrency and collection of nonfungible tokens, or NFTs. The big-box retailer filed several new trademarks late last month that indicate its intent to make and sell virtual goods, including electronics, home decorations, toys, sporting goods and personal care products. In a separate filing, the company said it would offer users a virtual currency, as well as NFTs. According to the U.S. Patent and Trademark Office, Walmart filed the applications on Dec. 30. In total, seven separate applications have been submitted. In a statement, Walmart said it is 'continuously exploring how emerging technologies may shape future shopping experiences.' It declined to comment on the specific trademark filings. 'We are testing new ideas all the time,' the company said. 'Some ideas become products or services that make it to customers. And some we test, iterate, and learn from.' 'They’re super intense,' said Josh Gerben, a trademark attorney. 'There’s a lot of language in these, which shows that there’s a lot of planning going on behind the scenes about how they’re going to address cryptocurrency, how they’re going to address the metaverse and the virtual world that appears to be coming or that’s already here.' Gerben said that ever since Facebook announced it was changing its company name to Meta, signaling its ambitions beyond social media, businesses have been rushing to figure out how they will fit into a virtual world. Launching NFTs allows for businesses to tokenize physical products and services to help reduce online transaction costs, it said. And for luxury brands like Gucci and Louis Vuitton, NFTs can serve as a form of authentication for tangible and more expensive goods, CB Insights noted. Gerben said that as more consumers familiarize themselves with the metaverse and items stored on the blockchain, more retailers will want to create their own ecosystem around it. According to Frank Chaparro, director at crypto information services firm The Block, many retailers are still reeling from being late to e-commerce, so they don’t want to miss out on any opportunities in the metaverse."
        },
        {
            id:"28",
            tittle:"Budget 2022-23: Govt likely to target 13-14% nominal growth in FY23",
            image:"/images/business/budget.jpg",
            date:"January 17, 2022",
            author:"By Asit Ranjan Mishra ",
            category:"Business",
            description:"The Union Budget for FY23 is likely to assume 13-14 per cent nominal GDP growth despite the growing inflationary concerns. According to finance ministry officials, the assumption of even faster nominal GDP growth may raise inflationary expectations, giving wrong signals to the market.",
            article:"For FY22, the Budget assumed 14.4 per cent gro­wth in nominal GDP. But the latest first Advance Esti­m­ates of GDP for the year released by the National Stati­stical Office put nominal GDP at 17.6 per cent, with an implicit GDP defl­ator of 8.4 per cent, signalling that the finance. Budget FY23 is likely to have two focal points: (1) striking a balance between fiscal consolidation and supporting economic activity, especially amid the uncertainty surrounding a new COVID-19 wave in FY23, and (2) any tax change announcements, which could pave the way for Euroclear eligibility for Indian government bonds (IGBs), and eventually, their inclusion in one of the major global bond indices. We believe the Centre is likely to announce a fiscal deficit target of 6% of GDP for FY23, assuming that the FY22 fiscal deficit target is in the range of 6.5-6.8% of GDP; we think the FY22 fiscal deficit is likely to be towards the lower end rather than the upper end of the band, as nominal GDP growth of 17.6% and tax collections have been much better than budgeted. The key question is whether such fiscal deficit consolidation will allow space for nurturing growth. We think so, for a host of reasons. Relative to the pre-pandemic phase, when the fiscal deficit ranged from 3.5-4% of GDP, a 6% fiscal deficit provides enough room to the government to support growth. However, one could argue that a 6% FY23 fiscal deficit target is probably only‘optically wider’, as GDP contracted in FY21. However, based on our estimate, even if we assume that GDP in FY20-FY23 grows in line with trend (five-year average GDP growth of FY15-19), expenditure as a percentage of GDP in FY23 would still be close to 13.5% of GDP versus the pre-pandemic average of 12.8% of GDP. It is equally interesting to note that while most of this increase in expenditure since the Covid outbreak has been driven by subsidies, interest payments, etc,capital expenditure has risen too. For instance, capital expenditure is hovering at around 2.1-2.2% of GDP since FY21 (we expect a similar trend in FY23) versus the pre-pandemic average of 1.7% of GDP."
        },
        {
            id:"25",
            tittle:"China’s economy grew 8.1% in 2021 compared to a year ago",
            image:"/images/business/chinagdp.jpeg",
            date:"January 15, 2022",
            author:"By Evelyn Cheng",
            category:"Business",
            description:"Fourth-quarter GDP rose by 4% from a year earlier, according to China’s National Bureau of Statistics. Analysts polled by Reuters had expected China to report fourth-quarter GDP growth of 3.6%.",
            article:"BEIJING — China’s economy grew by 8.1% in 2021 as industrial production rose steadily through the end of the year and offset a drop off in retail sales, according to official data from China’s National Bureau of Statistics released Monday. Fourth-quarter GDP rose by 4% from a year ago, according to the statistics bureau. That’s faster than the 3.6% increase forecast by a Reuters poll. For the full year, China economists expected an average of 8.4% growth in 2021, according to financial data provider Wind Information. Industrial production rose by 4.3% in December from a year ago, the bureau said, also beating Reuters’ forecast of 3.6% growth. Notably, auto production grew for the first time since April, up by 3.4% year-on-year in December. Fixed asset investment for 2021 grew by 4.9%, topping expectations for 4.8% growth. Investment in real estate rose by 4.4%, while that in infrastructure rose by 0.4%. Investment in manufacturing grew by 13.5% in 2021 from a year ago, with that in special purpose machinery rising the most, up by 24.3% year-on-year, according to data accessed through Wind. However, retail sales missed expectations and grew by 1.7% in December from a year ago. Analysts polled by Reuters had predicted a 3.7% increase. 'We must be aware that the external environment is more complicated and uncertain, and the domestic economy is under the triple pressure of demand contraction, supply shock and weakening expectations,' the bureau said in a statement."
        },
        {
            id:"23",
            tittle:"Indian CEOs worry more now about health risks impacting top line: PwC study",
            image:"/images/business/indianceo.jpg",
            date:"January 17, 2022",
            author:"By Asit Ranjan Mishra",
            category:"Business",
            description:"While 99% Indian CEOs polled this year believed India's economic growth will improve in next 12 months, the survey conducted before third wave outbreak raises fresh questions about the outlook",
            article:"About 89 per cent of India’s chief executive officers (CEOs) are concerned about health risks adversely impacting their top line in the next 12 months. This is 9 percentage points higher than what their global counterparts think, according to a CEO survey conducted by audit firm PwC before the onset of the third wave. “This is perhaps an indication that business leaders would like to exercise caution when it comes to making early investment and business decisions, despite vaccination drives worldwide. Concern over the ability to attract and retain talent is also strongly ...   As we near the two-year mark of the pandemic, the global economy has rebounded from the depths of mid-2020. The IMF projects global GDP to grow 4.9% in 2022, a downtick from the 5.9% growth expected in 2021, but still formidable. The 4,446 CEOs from 89 countries and territories who responded to our 25th Annual Global CEO Survey display optimism about continued economic resilience. Yet threats, uncertainties and tensions abound. The survey was in the field during the COP26 conference in Scotland, which convened world leaders to try to prevent the worst effects of climate change. PwC experts who attended were both impressed by executives’ commitment to rapid progress and aware that the captains of industry in Glasgow were a self-selected group that came prepared to take action. The question of how to bring others along looms large. Then, just two weeks after our survey closed, news of the Omicron variant reverberated around the world, raising fresh questions about the course of the pandemic and about society’s ability to continue the slow climb to normalcy. Our survey findings reflect these and other tensions. For example, just 22% of survey respondents have made net-zero commitments (though the largest companies in our sample are further along). CEOs are most worried about the potential for a cyberattack or macroeconomic shock to undermine the achievement of their company’s financial goals—the same goals that most executive compensation packages are still tied to. And they are less concerned about challenges, like climate change and social inequality, that appear to pose smaller immediate threats to revenue."
        }
    ])
return(
    <BusinessContext.Provider value={{business, top}} >
        {props.children}
    </BusinessContext.Provider>
)
}
export default BusinessContextProvider;