import { createContext, useState } from "react";

export const HollywoodContext = createContext()

const HollywoodContextProvider = (props) => {
    const [hollywood] = useState([{
        id: "61",
        tittle: "‘Spider-Man: No Way Home’ Lands at No. 4 on All-Time Box Office List",
        image: "/images/hollywood/Spiderman.jpg",
        date: "January 18, 2022",
        author: "BY PAMELA MCCLINTOCK",
        category: "Hollywood",
        description: "The Sony and Marvel superhero pic has crossed the $700 million mark at the domestic box office. Spider-Man: No Way Home has spun a history-making web at the domestic box office.",
        article: `The Sony and Marvel Studios superhero blockbuster on Monday became the fourth top-grossing film of all time — not adjusted for inflation — after passing up Black Panther to finish the day with $702.7 million in ticket sales, according to final numbers for the Martin Luther King Jr. holiday weekend. No Way Home is among only five films to earn $700 million or more domestically after Black Panther ($700.4 million), Avatar ($760.5 million), Avengers Endgame ($858.4 million) and Star Wars: The Force Awakens ($936.7 million). The performance of No Way Home, both in North America and overseas, is all the more remarkable considering the challenges posed by COVID-19. Globally, No Way Home sits at No. 8 on the all-time list of top-grossing films, with north of $1.63 billion in revenue as of Monday. There are several factors why the latest Spidey installment won’t achieve the same record levels worldwide as it has domestically, including the ongoing pandemic and the fact that it has yet to receive a release date in China. In North America, No Way Home will likely remain at No. 4. To climb any higher would mean overtaking Avatar, whose lifetime gross of $760.5 million includes more than $11 million in re-release grosses. No Way Home is the first film of the COVID-19 era to do pre-pandemic level business, thanks in large part to male moviegoers between the ages of 18 and 34.`
    },
    {
        id: "62",
        tittle: "The King’s Man movie review: Superspy origin story meets quirky alt-history",
        image: "/images/hollywood/kingsman.jpg",
        date: "January 14, 2022",
        author: "By Pradeep Menon",
        category: "Hollywood",
        description: "he King's Man is made for those that find themselves at the precise intersection of ‘Kingsman fan’ and ‘history nerd’.",
        article: `In the first Kingsman film, Galahad (Colin Firth) briefly tells Eggsy (Taron Egerton) about the World War I origins of the gentleman-spy organization fronted by the distinguished Kingsman Tailors of Savile Row, London. With the third film of the franchise, The King’s Man, director Matthew Vaughn returns to serve us that origin story in detail, complete with dollops of alt-history to spice things up. Now make no mistake, the Kingsman films are essentially superhero films, with fine bespoke suits in place of the shiny costumes one might be used to in other cinematic universes. I’d argue that Kingsman is a smidge more fun than other comic-based franchises; because despite the extreme action on display, both films so far kept the stakes as relatable as possible. Give me a tech magnate planting rogue chips in mobile phones worldwide or a drug lord aspiring to compete with Big Pharma, over Thanos and whatever he was up to any day of the week. (Wise-ass English folk over dumb-ass Americans is a no-brainer.) While I did miss Eggsy & Co in this period endeavour, Vaughn and co-writer Karl Gajdusek make up for it with a rather clever plot loaded with Easter eggs of all shapes and sizes. They’ve retained much of what worked for the franchise – the humour, the action, the (mostly) good manners – and placed it all in a spectacular setting that would have been considered unrealistic, if it wasn’t for the fact that many of the events in the film actually did happen, albeit over a century ago. And they didn’t just ‘happen’ – they shaped the world that we live in today.  will admit, though, that the Kingsman movies have a ‘too much of a good thing’ issue. At some point they can feel exhausting, because they are just relentless. Gut-wrenching deaths are routine, comedy is mostly non-negotiable, and even though you’ve suspended your disbelief to enjoy the cheeky action, it’ll still make you shake your head once in a while. This latest one is no different. Like its predecessors, it also clocks in at over two hours. A haircut would’ve done it a world of good. Still, against the odds, Kingsman continues to be a worthy franchise to follow. And yes, there’s more on the way. One probably wouldn’t trust a ‘white saviour’ from a mile away in real life today. But there’s something utterly delightful about these fictional non-partisan, non-governmental, British superspies trying to do right by the world. It’s probably the manners and the impeccable tailoring.`
    },
    {
        id: "63",
        tittle: "‘Star Trek: Strange New Worlds’ Renewed for Season 2 Ahead of Series Debut",
        image: "/images/hollywood/startrek.jpg",
        date: "January 18, 2022",
        author: "BY JAMES HIBBERD",
        category: "Hollywood",
        description: "In addition, 'Star Trek: Discovery' has been renewed for a fifth season, and premiere dates have been revealed for all three live-action 'Trek' shows.",
        article: `Two Star Trek shows received their orders for new seasons Tuesday. Paramount+ has renewed flagship series Star Trek: Discovery for a fifth season and, more unusually, renewed the upcoming spin-off Strange New Worlds for a second season before the first season debuts. In addition, the streamer announced premiere dates for Discovery, Strange New Worlds and season two of Picard. Discovery’s fourth season will return from its winter break with new episodes starting Thursday, Feb. 10. Picard will launch Thursday, March 3, and then Strange New Worlds will have its series debut Thursday, May 5. The scheduling strategy will keep fresh live-action Trek episodes on Thursday night from early February into the summer. On the animated front, Star Trek: Lower Decks will return this summer for its third season of 10 episodes, with the show renewed for a fourth season. Star Trek: Prodigy is currently airing its debut season on Thursday nights. “Four years ago, we made a promise to grow Star Trek into something it had never been before, and thanks to the incredibly hard work done by our many talented showrunners, writers, and directors, along with the extraordinary support of CBS Studios and Paramount+, we’re keeping our word,” said Alex Kurtzman, architect and executive producer, of the Star Trek franchise. “Now our current shows are set up for the future as we work to build Trek’s next phase of programming for years to come.” Strange New Worlds stars Anson Mount as Captain Christopher Pike as he leads the U.S.S. Enterprise in the years before Captain Kirk. The show is billed as a return to the classic planet-of-the-week space exploration format of the original Star Trek series. It also stars Rebecca Romijn as Number One and Ethan Peck as Science Officer Spock. Akiva Goldsman and Henry Alonso Myers are co-showrunners of the CBS Studios series.`
    },
    {
        id: "64",
        tittle: "Oscars 2022 to have a host first time since 2018, broadcaster ABC says",
        image: "/images/hollywood/oscar.webp",
        date: "January 12, 2022",
        author: "By Agence France-Presse",
        category: "Hollywood",
        description: "The 94th Academy Awards, scheduled for 27 March, will see Tinseltown's most important prize-giving event return to its traditional Dolby Theatre venue in Hollywood. ",
        article: `Last year's unorthodox edition, held at a Los Angeles train station with no host, was watched by just over 10 million viewers -- a 56 percent decline from 2020, which was already a record low. "You heard it here first, I can confirm that this year's Oscars will have a host," Craig Erwich, president of ABC Entertainment and Hulu Originals, told a virtual panel discussion hosted by the Television Critics Association. Erwich declined to give any further details, including whether Jimmy Kimmel -- host of ABC's Jimmy Kimmel Live! and the last two hosted Oscars in 2017 and 2018 -- will return. "It might be me," he quipped. In 2019, comedian Kevin Hart pulled out of hosting the Academy Awards after homophobic tweets he made several years earlier reemerged. He was not replaced, and while that year's hostless format drew praise and was even emulated by other awards shows such as the Emmys, subsequent Oscar ceremonies were criticised for lacking focus and humour. Also on Tuesday, the Academy of Motion Picture Arts and Sciences announced that veteran Glenn Weiss will direct the Oscars for a seventh consecutive year. Few details have been confirmed for the show, which will be produced by Will Packer and were postponed for a second consecutive year. The delay, reportedly to avoid clashing with February's Winter Olympics and the Super Bowl in Los Angeles, was announced months before the Omicron variant forced multiple Hollywood shows to scrap in-person events this winter.`
    },
    {
        id: "65",
        tittle: "‘Book of Boba Fett’ Stars React to Biker Gang Controversy: “These Things Are Out of Our Control”",
        image: "/images/hollywood/boba.jpg",
        date: "January 14, 2022",
        author: "BY JAMES HIBBERD",
        category: "Hollywood",
        description: "Temuera Morrison and Ming-Na Wen discussed that rather colorful biker gang and the show's Tusken Raiders controversy during a TCA Winter Press Tour panel.",
        article: `The Book of Boba Fett stars Temuera Morrison and Ming-Na Wen weighed in on a couple of the show’s very modest controversies during their virtual Television Critics Association press tour panel on Friday. First up, the duo were asked about criticisms of the Disney+ Star Wars show’s handling of its Tusken Raider characters. During the first three episodes, a tribe of the desert-dwelling warriors taught Boba Fett (Morrison) their ways. The tribe was then abruptly killed off, and Fett solemnly burned their bodies. The Raiders were portrayed as simple-minded brutes in the Star Wars films, and both The Mandalorian and The Book of Boba Fett have been praised for handling the Indigenous characters with more humanity. But their deaths drew some backlash online. “[Their portrayal] was better than it was [in the films],” Morrison said. “Then I read [in the script that] we were throwing dead bodies just on the fire and I was going, ‘Oh, hang on, we got to put a bit of ceremony into this.’ But they are the Indigenous of the sands of Tatooine, and I was creating a little bit more history about their own culture — and I was pulling from my own culture, in a way, in terms of the ceremonies and preparing the warrior and preparing a weapon. And Boba has never experienced a real family before — with the young Tuskens and the old Tuskens — and protecting their land.” Added Wen: “We knew so little about the Tuskens, and [the show] really gave them an incredible backstory. … I thought all those elements really enrich who the Tuskens are, … and [setting the bodies on fire] was part of Star Wars, with A New Hope, whether it’s the Jawas, when they were attacked, there is this ceremonious desire on Tatooine to burn the bodies as opposed to letting them lie out in the open in the desert.” Another issue raised by a critic was episode three’s instantly notorious biker gang that some fans compared to the Power Rangers. In the episode, a group of Tatooine street kids (including Yellowjackets star Sophie Thatcher) aid Boba Fett while riding colorful, shiny, Vespa-like hover-scooters.`
    },
    {
        id: "66",
        tittle: "‘The White Lotus’ Adds F. Murray Abraham, Adam DiMarco, Tom Hollander and Haley Lu Richardson to Season 2 Cast",
        image: "/images/hollywood/whitelotus.jpg",
        date: "January 18, 2022",
        author: "BY LESLEY GOLDBERG",
        category: "Hollywood",
        description: "They join the previously announced castmembers Michael Imperioli and Aubrey Plaza in HBO dark comedy, which sources say will now be set in Italy.",
        article: `The White Lotus season two is coming into sharper focus. Mike White’s HBO dark comedy has enlisted F. Murray Abraham, Adam DiMarco, Tom Hollander and Haley Lu Richardson as series regulars for its sophomore season. They join the previously announced castmembers Michael Imperioli and Aubrey Plaza in season two, which will leave Hawaii behind and be set at a different White Lotus hotel property. Sources say season two will be set in Italy, though HBO has declined comment on the setting. Abraham, whose massive list of credits includes Apple’s Mythic Quest, Showtime’s Homeland and features The Grand Budapest Hotel and Amadeus, will play Bert Di Grasso, an elderly man traveling with his son and grandson. DiMarco will portray Albie Di Grasso, a recent college grad who is traveling with his father and grandfather. His credits include Netflix’s The Order and Syfy’s The Magicians. Imperioli plays Dominic Di Grasso, Albie’s father and Bert’s son. Hollander is set as Quentin, an English expat who is vacationing with his friends and his nephew. The actor has had roles in The King’s Man, Pride & Prejudice, Gosford Park and Pirates of the Caribbean: At World’s End. Richardson joins the cast as Portia, a young woman who is traveling with her boss. Her credits include The Edge of Seventeen, Unpregnant and Five Feet Apart. Plaza, whose casting was announced last week, plays Harper Spiller, a woman on vacation with her husband and friends. Season two is rumored to feature the return of season one fan favorite Jennifer Coolidge, though HBO has declined to comment on her involvement. White again serves as writer, director and exec producer. David Bernad and Mark Kamine also exec produce. Abraham is repped by Innovative Artists and Franklin Weinrib. DiMarco is with the Characters Talent Agency and Canopy Media Partners. Hollander is with Anonymous Content and United Agents. Richardson is with Gersh, 3 Arts and Sloane Offer.`
    },
    {
        id: "67",
        tittle: "Marvel Studios ‘Shang-Chi’ And Japanese Film ‘Drive My Car’ Top 2022 Gold List",
        image: "/images/hollywood/sang.jpg",
        date: "January 18, 2022",
        author: "By Sara Merican",
        category: "Hollywood",
        description: "Returning for its second edition, the 2022 Gold List highlights outstanding work by Asian filmmakers and talent. Marvel Studios’ Shang-Chi and the Legend of the Ten Rings leads in the Best Picture.",
        article: `The Gold List is a collaboration between Gold House and CAPE (Coalition of Asian Pacifics in Entertainment) and spans 13 categories, with two new categories included this year, compared to the inaugural 2021 list. It seeks to ensure that a wider diversity of works is given proper recognition during the entertainment industry’s awards season, which culminates with the 94th Academy Awards on March 27. Other winners in this year’s list include The Rescue for Best Documentary Feature, Flee for Best Original Screenplay and Raya and the Last Dragon for Best Animated Feature. “Many Asian-led films, particularly independent films, don’t receive budgets or backing to run expensive For Your Consideration campaigns—or benefit from certain levels of access that are essential in ensuring nominations and eventual wins,” shared Jeremy Tran, Executive Director of Gold House. “Gold List, voted on by top Asian leaders and creatives in Hollywood—celebrates our community’s most outstanding achievements in the film industry and encourages voters to Consider Gold. In another pandemic year when so much gets lost and blended together, it’s even more imperative that we help worthy art break out.” Prizes given out at the Academy Awards, BAFTAs, Directors Guild of America and Producers Guild of America ceremonies, among others, bestow far more than recognition and limelight. They are seen as the film industry’s barometer for success and value—how gatekeepers read the tides of the content business, observe what their peers are thinking, and attempt to forecast where the cultural currents might flow next. Therefore, these awards significantly influence what kinds of films will continue to be greenlit, which directors and talent will be given top projects and ultimately, what—and whose—stories audiences get to watch. The Gold List voting body is made up of prominent leaders from the Gold Open Advisory Council, Gold House Members, CAPE Board Members and Advisors, and other entertainment industry heavyweights. “From elevating writers and creative executives, we’ve been focused on systemic changes that enable great creativity. But that’s only half the battle—we must also ensure that our projects are recognized, particularly in forums where our communities have often been overlooked,” said Michelle K. Sugihara, Executive Director of CAPE. “We hope the Gold List prompts voters to consider Asian films and creatives when deciding awards recognition.”`
    },
    {
        id: "68",
        tittle: "Netflix to Release 25 Korean Originals in 2022",
        image: "/images/hollywood/korean.jpg",
        date: "January 18, 2022",
        author: "BY PATRICK BRZESKI",
        category: "Hollywood",
        description: "Following the smash success of 'Squid Game,' the company is expected to easily surpass the half a billion dollars it spent on Korean content in 2021.",
        article: `Buoyed by the smash success of Squid Game, Hellhound and half a dozen other shows, Netflix is predictably doubling down on Korean content in 2022. The streamer said Wednesday that it will release 25 Korean films and series this year, its largest annual slate from the country to date. In 2021, Netflix invested over half a billion dollars in Korean content, and this year’s slate will easily surpass that spending figure, although the company has not released a precise estimate. The company did share a rash of numbers to explain its extreme bullishness on K-content. Netflix said global viewing hours for its Korean shows — it produced and released a total of 15 Korean originals last year — grew six-fold compared to 2019. Squid Game, of course, became Netflix’s most-watched series ever, with 95 percent of its viewership coming from outside Korea. Crucially for the streamer’s strategy, the company noted that “many of these viewers went on to explore other Korean content.” Hits that followed Squid Game‘s lead included the dark fantasy series Hellbound, which ranked number one on Netflix’s Top 10 in 34 countries. Sci-fi mystery The Silent Sea also made it to the number one spot on the weekly Top 10 lists for non-English content. “We are excited to continue collaborating with Korean storytellers to bring the K-wave to new heights,” said Don Kang, Netflix’s vp of content for Korea. Some of the highlights of Netflix’s coming Korean slate include All of Us Are Dead, in which zombies invade a high school; Money Heist: Korea – Joint Economic Area, an adaptation of the hit Spanish genre series; and action film Seoul Vibe, about the adventures of a special-ops team set against the backdrop of the 1988 Seoul Olympic Games. Netflix has carved out a commanding lead as the go-to global platform for Korean content fans — the service has launched more than 130 Korean titles to date — but competition from international rivals is ramping up. Disney+ unveiled a slate of seven Korean originals when it went live in South Korea and other Asian territories last fall, and Warner Media’s HBO Max will undoubtedly invest heavily in the category when it eventually launches in East Asia sometime this year.`
    }
    ])
    return (
        <HollywoodContext.Provider value={{ hollywood }} >
            {props.children}
        </HollywoodContext.Provider>
    )
}
export default HollywoodContextProvider;