import { createContext,useState } from "react";

export const SportsContext = createContext()

const SportsContextProvider =(props)=>{
        const [sports] =useState([{
            id:"41",
            tittle:"FPC wrestling team advances to state duals tournament",
            image:"/images/sports/fpc.jpeg",
            date:"January 17, 2022",
            author:"By Brent Woronoff",
            category:"Sports",
            description:"FPC wrestling coach Zach Sanford was home quarantining, and celebrating, when the Bulldogs won their regional quarterfinal and semifinal matches on Jan. 13 to advance to the state duals tournament for the first time.",
            article:"He pre-celebrated before the season when he saw that state power Fleming Island had dropped down to Class 2A. Fleming Island has been a regional foe since the FHSAA added a duals state tourney in 2018.  We've always been stuck behind Fleming, Sanford said. As soon as I saw they moved to 2A, I said, We re gonna go to states. And they are. They will meet Oviedo Hagerty in the Region 1-3A final on Friday, Jan. 21 at the state duals tournament at Kissimmee Osceola High School. The winner will advance to the Class 3A state semifinals on Jan. 22 against Wellington or Fort Pierce Central, with the championship match following. Last week, the Bulldogs traveled to Creekside High School in St. Johns where they defeated Oakleaf 45-27 in a regional quarterfinal and then knocked off district foe DeLand 42-36 in the semifinal. The 1-2-3-4 punch was too much for those other Bulldogs. Tim King (152), Bryce Dodge (160), Blane DeFord (170) and Marcel Gonzalez (182) all pinned their opponents. Seth Davis (285) won by decision in the semifinal's second match. Kole Hannant (120) and John Hald (126) also pinned their opponents, and Garrick Schwartz (195) clinched the victory over DeLand with a 3-1 decision. Sanford expects to be back with his team for state. Matanzas' boys wrestling team saved a couple of secret weapons for their regional duals — a couple of freshmen who had never wrestled against boys in a high school competition. Mariah Mills and Tianna Fries mowed down their opponents as easily as they have in matches against girls. They each recorded pins against host Neptune Beach Fletcher in the Region 1-2A quarterfinals on Jan. 13. 'It's something we'd been thinking about for a while,' coach T.J. Gillin said. 'We have all the confidence in the world in them. They get after it hard. They're the full package. Without Mariah and Tianna, we don't get past Fletcher.'"
        },
        {
            id:"42",
            tittle:"India look to bounce back from Test series defeat, all eyes on Virat Kohli ‘the batter’",
            image:"/images/sports/klrahul.webp",
            date:"January 18, 2022",
            author:"By Saurabh Kumar",
            category:"Sports",
            description:"SA vs IND: The focus will shift on Virat Kohli 'the batter' when KL Rahul-led Indian team takes on Temba Bavuma's South Africa in the three-match ODI series.",
            article:"he KL Rahul-led Indian team will look to bounce back from the shocking Test series defeat when they take on hosts South Africa in a three-match ODI series, starting on Wednesday in Paarl. On the previous tour, India hammered the hosts 5-1 in ODIs and they will draw confidence from it when they face the Temba Bavuma-led side in Paarl. Also, Virat Kohli, 'the batter', will be keenly followed as he takes on the field as a mere player for the first time in seven years. Not only does Kohli have a major role to play as a batter, but as vice-captain Jasprit Bumrah said on the eve of the series, the star 'will always be a leader' in the team. India will look to win the series with one eye on preparations for the 2023 World Cup and also make up for the disappointment of unexpectedly going down in the Tests last week. India had to contend with pace and bounce in their 2-1 Test series loss to South Africa but will find conditions more like home in Paarl. India have not selected a full-strength squad for an ODI series since their 2-1 home win over England in March. Rahul, who is leading the side in the absence of an injured Rohit Sharma, is expected to turn to Kohli for advice during the series. This series is the start of their build-up to the 2023 Cricket World Cup that India will host. 'We have sat down as a team and had an honest talk about what are the things we can improve and what we can get better at. Everyone is committed to it. We have the World Cup in mind and we have a process we have all decided to follow,' Rahul said. 'All these games become really important for us to go out there and try and grow as a team, and do all the things that we spoke about. We won't be a team that is scared to try a few things because our focus is on the World Cup and to try and get the best team out on the park.' Meanwhile, South Africa will look to gain momentum from their memorable series win over India in the five-day format. Skipper Temba Bavuma played a few crucial games in the preceding Tests and he will carry that confidence into his batting as well as his leadership. Quinton de Kock, who retired from Test cricket after the series opener against India, starts his life as a white-ball only player. Tall left-arm pacer Marco Jansen, who excelled in his maiden Test series, is expected to trouble the Indian batters with his extra bounce and variations in the short format after earning a maiden call-up."
        },
        {   
            id:"43",
            tittle:"Asian Cup women’s football: Cop-turned-coach Dennerby aiming to guide India past group stage",
            image:"/images/sports/Dennerby.jpg",
            date:"January 18, 2022",
            author:"By Mihir Vasavda",
            category:"Sports",
            description:"Dennerby, the first foreign coach of India’s women team, faces an unenviable task: to take an inexperienced team, which is brimming with potential, past the group stage in its first appearance at the Asian Cup since 2003.",
            article:"Nothing about Thomas Dennerby suggests he is a former cop who takes no-nonsense. The Swede laughs easily, speaks in a soft, comforting tone and says, with a smile, he is kind. 'That’s what a lot of people tell me,' he grins. 'That job gave me a different perspective on life…' On night patrols, Dennerby the policeman had brushes with hardened criminals, intervened in ugly family fights and even prevented suicides. In the mornings, after dealing with the real-world issues, coach Dennerby wouldn’t have the heart to yell at his players for merely missing a pass. 'What is more important?' he asks, rhetorically. 'That job changed me as a person.' For a fortnight, starting Thursday, the good cop will patrol the Indian women football team’s dugout in the Asian Cup. The continental championship, which is also a 2023 World Cup qualifier, will kick off on Thursday with a clash between the competition’s most successful team, 8-time champions China, and Chinese Taipei in Mumbai. Later in the day, India will open their campaign against Iran in Navi Mumbai. Dennerby, the first foreign coach of India’s women team, faces an unenviable task: to take an inexperienced team, which is brimming with potential, past the group stage in its first appearance at the Asian Cup since 2003. 'Our first target is to reach the quarterfinals,' he tells The Indian Express. 'But first, we have to put a good performance against Iran and then see what happens. It’s thrilling, it’s fine, it’s nice. When it comes to elite sports, you want to be on the big scene.' The 62-year-old is familiar with the highs of playing on the ‘big scene’. As the coach of Sweden women, Dennerby made up for a group-stage exit at the 2007 World Cup by finishing third in the 2011 edition. It was only the third time Sweden had reached the semifinals of a World Cup. He also was Sweden’s coach at the 2008 and 2012 Olympics; both times, they were knocked out in the quarterfinals. Then, as the coach of Nigerian women, he guided the team to the women’s African Cup of Nations title in 2018 and, the following year, steered them to the quarterfinals of the World Cup for the first time in 20 years."
        },
        {
            id:"44",
            tittle:"Palm Coast Rowing hosts Syracuse University crew teams",
            image:"/images/sports/palm.png",
            date:"January 13, 2022",
            author:"By Guest",
            category:"Sports",
            description:"The Palm Coast Rowing Club is hosting 90 student athletes and coaches from Syracuse University for a week of winter training. The teams will be training on the Intracoastal through the end of the week.",
            article:"The men's and women's crew teams can be seen mornings from 8-10 and afternoons 3-5 on the Intracoastal Waterway in 8-person and 4-person shells with coaching boats. Good views can be found from the toll bridge, the bridge over Palm Harbor Parkway, the marina near Palm Coast Resort and Yacht Harbor. Syracuse will be on the water through the end of this week. The Syracuse University crew teams appreciates Palm Coast's miles of navigable and scenic rowing in calm waters and warm temperatures. The Syracuse University crew teams appreciates Palm Coast's miles of navigable and scenic rowing in calm waters and warm temperatures. For members of the community who are interested in learning the sport, the next session of Learn to Row begins Wednesday, Jan. 19 with both indoor and on the water training. Syracuse University mens' and womens' crew teams are in Palm Coast this week for winter practice. I've seen them mostly in the early morning when the water is calm and motorized boat traffic is at a minimum. I grew up near Rochester, N.Y. and lived in Cazenovia, near Syracuse, for seven years. I understand well their reasons for coming to Palm Coast at his time of the year."
        },
        {
            id:"45",
            tittle:"Olympic athletes urged by activists not to criticize China",
            image:"/images/sports/olympic.jpeg",
            date:"January 18, 2022",
            author:"By GRAHAM DUNBAR",
            category:"Sports",
            description:"GENEVA (AP) — Athletes at the Beijing Olympics were urged by human rights activists Tuesday to avoid criticizing China because they could be prosecuted.",
            article:`The International Olympic Committee has said athletes will have freedom of speech at next month’s Winter Games when speaking to journalists or posting on social media. However, the Olympic Charter rule that prohibits political protests at medal ceremonies also requires “applicable public law” to be followed. The IOC has not yet publicly committed to how athletes who speak out would be protected, activists said in a briefing hosted by Human Rights Watch. “Silence is complicity and that’s why we have concerns,” said Rob Koehler, the director general of the Global Athlete group. “We know the human rights record and the allowance of freedom of expression in China, so there’s really not much protection.” The IOC has not responded to requests in recent days to clarify how Chinese law could apply at the Beijing Games, which open on Feb. 4. “Chinese laws are very vague on the crimes they can use to prosecute people’s free speech,” Human Rights Watch researcher Yaqiu Wang said, citing potential offenses of provoking trouble or inciting subversion. China’s treatment of its Muslim-majority Uyghur people and polices toward Tibet, Hong Kong and Taiwan have come under increased scrutiny ahead of the Olympics. China also drew criticism following the near-total disappearance from public view of tennis player Peng Shuai. She wrote in a social media post that she was sexually assaulted by a former senior member of the ruling Communist Party. Two-time Olympic cross-country skier Noah Hoffman said he knew the United States team was now shielding its athletes from facing questions. “That makes me upset and I am scared for their safety when they go to China,” Hoffman said. “They can speak out when they get back.” Activists cited the cases of Peng, wrestler Navid Afkari, who was executed in Iran in 2020, and the treatment of athletes by the authoritarian regime in Belarus as examples where the IOC could have done more to protect athletes.`
        },
        {
            id:"46",
            tittle:"ISL 2021/22: Ishan Pandita's injury-time winner hands Jamshedpur 3-2 win over NorthEast United",
            image:"/images/sports/isl.jpeg",
            date:"January 18, 2022",
            author:"By Rohit Mundayur",
            category:"Sports",
            description:"ISL 2021/22: Ishan Pandita proved to be a super-sub again as he made no mistake in finishing from close range and secured three vital points for his team.Jamshedpur carried their momentum from the first half into the second.",
            article:"An injury-time winner from Ishan Pandita helped Jamshedpur FC secure a 3-2 win over NorthEast United in the 2021/22 Indian Super League (ISL) at the Athletic Stadium in Bambolim. The result elevates Owen Coyle’s men to third place in the league table, level on points with second-placed Mumbai City FC and leaders Hyderabad FC. Deshorn Brown (4') broke the deadlock with an early strike until Jordan Murray (44') levelled the score with a header. Boris Singh (56') then sent JFC into the lead with his first-ever goal in the ISL. Brown (90+1') looked to have secured a draw with a late goal until Ishan Pandita (90+3') scored the winner deep into injury time. The match began with the Highlanders grabbing a hold on the proceedings. Deshorn Brown scored his fifth goal of the campaign inside the first five minutes. The striker was fed by Suhair Vadakkepeedika with a penetrating pass and found himself in a one-on-one situation with the goalkeeper. He calmly placed his right-footed shot in the bottom left corner for the early breakthrough goal. A few minutes later, Jordan Murray missed an open goal with a diving header, thus wasting a great chance to score the equalizer. A few moments later, calls for a penalty were denied by the referee when Provat Lakra seemingly tripped Greg Stewart inside the box. The forward had another chance to score the equalizer but his left-footed shot was parried away by Mirshad Michu. However, the goal finally came from Jordan Murray who leapt the highest to connect with Stewart’s free-kick and head the ball inside the net in the closing stages of the first half. Jamshedpur carried their momentum from the first half into the second. Within three seconds of the restart, Murray’s shot from the right corner of the box required Michu’s intervention who made a strong save. JFC finally took the lead five minutes before the hour mark following a goal from Boris Singh. The winger latched on to a cut-back from Murray and made no mistake in placing the ball inside an empty goal with his right foot. Just as five minutes were added for stoppages, Brown scored his second after weaving past the goalkeeper and scoring with immense composure. A couple of minutes later, Ishan Pandita scored the winner, acting as the super-sub yet again. The striker made no mistake in finishing from close range and secured three vital points for his team."
        },
        {
            id:"47",
            tittle:"Novak Djokovic to be deported from Australia, court upholds tennis star's visa cancellation",
            image:"/images/sports/novak.webp",
            date:"January 16, 2022",
            author:"By Rohit Mundayur",
            category:"Sports",
            description:"Men's tennis world No.1 Novak Djokovic faces deportation from Australia as his visa cancellation was upheld by the country's Federal Court. The Serbian tennis great thus loses a chance to defend his Australian Open title.",
            article:`Men's tennis World No.1 Novak Djokovic is set to be deported from Australia after the Federal Court upheld the country's government's decision to cancel his visa on Sunday. Djokovic, who was chasing a record 21st Grand Slam title at the 2022 Australian Open and looking to defend his title as well, will now not be able to participate in the tournament. A three-judge bench of the Federal Court heard government lawyers' arguments that Djokovic's continued presence risked whipping up anti-vaccination sentiment during Australia's worst outbreak of COVID-19 since the pandemic began. Djokovic holds the record for most titles at the Australian Open, having won the tournament for the ninth time in 2021. He was escorted to his lawyers' office by immigration officials to attend the virtual court hearing on Sunday morning, having spent Saturday night back in an immigration detention hotel. A medical exemption that allowed Djokovic to enter the country without being vaccinated had sparked fury in Australia, and became a political issue for Prime Minister Scott Morrison, who has to call a federal election before May. Australia's Immigration Minister Alex Hawke cancelled his visa on the grounds that Djokovic's presence in Australia may be a risk to the health and "good order" of the Australian public and “may be counterproductive to efforts at vaccination by others in Australia.” Djokovic’s visa was initially cancelled on January 6 at Melbourne’s airport hours after he arrived to compete in the first Grand Slam of 2022. A border official cancelled his visa after deciding that the Serbian tennis great didn’t qualify for a medical exemption from Australia’s rules for unvaccinated visitors.`
        },
        {
            id:"48",
            tittle:"Stafford propels Rams past Cardinals 34-11 in playoff rout",
            image:"/images/sports/Rams.jpeg",
            date:"January 19, 2022",
            author:"By GREG BEACHAM ",
            category:"Sports",
            description:"The Rams had a 20-point lead on Arizona with 4 1/2 minutes left at raucous SoFi Stadium. Matthew Stafford’s 13-year quest for his first playoff victory was all but complete after Los Angeles’ dominant performance on both sides of the ball.",
            article:`The quarterback still took off running on third-and-long through the heart of the Cardinals’ defense on a gleeful, perilous scramble that ultimately ended short of a first down. Even while shouldering enormous postseason pressure, Stafford never forgot to have fun. He was strong enough to carry it all — and the Rams are riding him on to Tampa Bay. Stafford passed for 202 yards and two touchdowns and ran for another score in his first playoff win, and the Rams roared out of the wild-card round with a 34-11 victory over Arizona on Monday night. “What a team effort,” Stafford said. “Our defense played outstanding tonight. Special teams basically set up a score ... and we were good enough on offense to score some points and come away with the win Just happy to be moving on.” Odell Beckham Jr. and Cooper Kupp made touchdown catches for the NFC West champion Rams (13-5), who will visit the defending Super Bowl champion Buccaneers on Sunday for a spot in the NFC championship game. David Long also scored on a 3-yard interception return while the Rams’ defense harassed Kyler Murray into a calamitous playoff debut. Los Angeles led 28-0 before cruising in the first playoff game at SoFi, which will host Super Bowl 56 next month. Stafford was outstanding in his first playoff game with the Rams, completing 13 of his season-low 17 passes without an interception and despite three drops. He scored his first playoff rushing TD since January 2012 on a goal-line sneak, and he coolly directed LA’s offense while seizing his first playoff win in a career that began with 12 years in Detroit, where his Lions went 0-3 in the postseason. “I thought he did a great job leading the way,” McVay said. “He’s still the same great player to me, and he always was before this game. I think it’s good so you guys don’t have to talk about that anymore. So pleased be able to do this with him. He’s our leader out there, and we wouldn’t be here without him.”`
        }
    ])
return(
    <SportsContext.Provider value={{sports}} >
        {props.children}
    </SportsContext.Provider>
)
}
export default SportsContextProvider;